/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoilerRouteImport } from './routes/boiler'
import { Route as CedRouteImport } from './routes/ced'
import { Route as ChecksheetRouteImport } from './routes/checksheet'
import { Route as ChecksheetApprovalRouteImport } from './routes/checksheet-approval'
import { Route as ChecksheetDailyRouteImport } from './routes/checksheet-daily'
import { Route as LogHistoryRouteImport } from './routes/log-history'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as MonitoringAreaRouteImport } from './routes/monitoring-area'
import { Route as OvenRouteImport } from './routes/oven'
import { Route as ReportRouteImport } from './routes/report'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as BoilerDetailsIdRouteImport } from './routes/boiler-details.$id'
import { Route as MonitoringAreaIdRouteImport } from './routes/monitoring-area.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoilerRoute = BoilerRouteImport.update({
  id: '/boiler',
  path: '/boiler',
  getParentRoute: () => rootRouteImport,
} as any)
const CedRoute = CedRouteImport.update({
  id: '/ced',
  path: '/ced',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksheetRoute = ChecksheetRouteImport.update({
  id: '/checksheet',
  path: '/checksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksheetApprovalRoute = ChecksheetApprovalRouteImport.update({
  id: '/checksheet-approval',
  path: '/checksheet-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksheetDailyRoute = ChecksheetDailyRouteImport.update({
  id: '/checksheet-daily',
  path: '/checksheet-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const LogHistoryRoute = LogHistoryRouteImport.update({
  id: '/log-history',
  path: '/log-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringAreaRoute = MonitoringAreaRouteImport.update({
  id: '/monitoring-area',
  path: '/monitoring-area',
  getParentRoute: () => rootRouteImport,
} as any)
const OvenRoute = OvenRouteImport.update({
  id: '/oven',
  path: '/oven',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BoilerDetailsIdRoute = BoilerDetailsIdRouteImport.update({
  id: '/boiler-details/$id',
  path: '/boiler-details/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringAreaIdRoute = MonitoringAreaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MonitoringAreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boiler': typeof BoilerRoute
  '/ced': typeof CedRoute
  '/checksheet': typeof ChecksheetRoute
  '/checksheet-approval': typeof ChecksheetApprovalRoute
  '/checksheet-daily': typeof ChecksheetDailyRoute
  '/log-history': typeof LogHistoryRoute
  '/master-data': typeof MasterDataRoute
  '/monitoring-area': typeof MonitoringAreaRouteWithChildren
  '/oven': typeof OvenRoute
  '/report': typeof ReportRoute
  '/user-management': typeof UserManagementRoute
  '/boiler-details/$id': typeof BoilerDetailsIdRoute
  '/monitoring-area/$id': typeof MonitoringAreaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boiler': typeof BoilerRoute
  '/ced': typeof CedRoute
  '/checksheet': typeof ChecksheetRoute
  '/checksheet-approval': typeof ChecksheetApprovalRoute
  '/checksheet-daily': typeof ChecksheetDailyRoute
  '/log-history': typeof LogHistoryRoute
  '/master-data': typeof MasterDataRoute
  '/monitoring-area': typeof MonitoringAreaRouteWithChildren
  '/oven': typeof OvenRoute
  '/report': typeof ReportRoute
  '/user-management': typeof UserManagementRoute
  '/boiler-details/$id': typeof BoilerDetailsIdRoute
  '/monitoring-area/$id': typeof MonitoringAreaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boiler': typeof BoilerRoute
  '/ced': typeof CedRoute
  '/checksheet': typeof ChecksheetRoute
  '/checksheet-approval': typeof ChecksheetApprovalRoute
  '/checksheet-daily': typeof ChecksheetDailyRoute
  '/log-history': typeof LogHistoryRoute
  '/master-data': typeof MasterDataRoute
  '/monitoring-area': typeof MonitoringAreaRouteWithChildren
  '/oven': typeof OvenRoute
  '/report': typeof ReportRoute
  '/user-management': typeof UserManagementRoute
  '/boiler-details/$id': typeof BoilerDetailsIdRoute
  '/monitoring-area/$id': typeof MonitoringAreaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boiler'
    | '/ced'
    | '/checksheet'
    | '/checksheet-approval'
    | '/checksheet-daily'
    | '/log-history'
    | '/master-data'
    | '/monitoring-area'
    | '/oven'
    | '/report'
    | '/user-management'
    | '/boiler-details/$id'
    | '/monitoring-area/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boiler'
    | '/ced'
    | '/checksheet'
    | '/checksheet-approval'
    | '/checksheet-daily'
    | '/log-history'
    | '/master-data'
    | '/monitoring-area'
    | '/oven'
    | '/report'
    | '/user-management'
    | '/boiler-details/$id'
    | '/monitoring-area/$id'
  id:
    | '__root__'
    | '/'
    | '/boiler'
    | '/ced'
    | '/checksheet'
    | '/checksheet-approval'
    | '/checksheet-daily'
    | '/log-history'
    | '/master-data'
    | '/monitoring-area'
    | '/oven'
    | '/report'
    | '/user-management'
    | '/boiler-details/$id'
    | '/monitoring-area/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoilerRoute: typeof BoilerRoute
  CedRoute: typeof CedRoute
  ChecksheetRoute: typeof ChecksheetRoute
  ChecksheetApprovalRoute: typeof ChecksheetApprovalRoute
  ChecksheetDailyRoute: typeof ChecksheetDailyRoute
  LogHistoryRoute: typeof LogHistoryRoute
  MasterDataRoute: typeof MasterDataRoute
  MonitoringAreaRoute: typeof MonitoringAreaRouteWithChildren
  OvenRoute: typeof OvenRoute
  ReportRoute: typeof ReportRoute
  UserManagementRoute: typeof UserManagementRoute
  BoilerDetailsIdRoute: typeof BoilerDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boiler': {
      id: '/boiler'
      path: '/boiler'
      fullPath: '/boiler'
      preLoaderRoute: typeof BoilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ced': {
      id: '/ced'
      path: '/ced'
      fullPath: '/ced'
      preLoaderRoute: typeof CedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checksheet': {
      id: '/checksheet'
      path: '/checksheet'
      fullPath: '/checksheet'
      preLoaderRoute: typeof ChecksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checksheet-approval': {
      id: '/checksheet-approval'
      path: '/checksheet-approval'
      fullPath: '/checksheet-approval'
      preLoaderRoute: typeof ChecksheetApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checksheet-daily': {
      id: '/checksheet-daily'
      path: '/checksheet-daily'
      fullPath: '/checksheet-daily'
      preLoaderRoute: typeof ChecksheetDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-history': {
      id: '/log-history'
      path: '/log-history'
      fullPath: '/log-history'
      preLoaderRoute: typeof LogHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring-area': {
      id: '/monitoring-area'
      path: '/monitoring-area'
      fullPath: '/monitoring-area'
      preLoaderRoute: typeof MonitoringAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oven': {
      id: '/oven'
      path: '/oven'
      fullPath: '/oven'
      preLoaderRoute: typeof OvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boiler-details/$id': {
      id: '/boiler-details/$id'
      path: '/boiler-details/$id'
      fullPath: '/boiler-details/$id'
      preLoaderRoute: typeof BoilerDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring-area/$id': {
      id: '/monitoring-area/$id'
      path: '/$id'
      fullPath: '/monitoring-area/$id'
      preLoaderRoute: typeof MonitoringAreaIdRouteImport
      parentRoute: typeof MonitoringAreaRoute
    }
  }
}

interface MonitoringAreaRouteChildren {
  MonitoringAreaIdRoute: typeof MonitoringAreaIdRoute
}

const MonitoringAreaRouteChildren: MonitoringAreaRouteChildren = {
  MonitoringAreaIdRoute: MonitoringAreaIdRoute,
}

const MonitoringAreaRouteWithChildren = MonitoringAreaRoute._addFileChildren(
  MonitoringAreaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoilerRoute: BoilerRoute,
  CedRoute: CedRoute,
  ChecksheetRoute: ChecksheetRoute,
  ChecksheetApprovalRoute: ChecksheetApprovalRoute,
  ChecksheetDailyRoute: ChecksheetDailyRoute,
  LogHistoryRoute: LogHistoryRoute,
  MasterDataRoute: MasterDataRoute,
  MonitoringAreaRoute: MonitoringAreaRouteWithChildren,
  OvenRoute: OvenRoute,
  ReportRoute: ReportRoute,
  UserManagementRoute: UserManagementRoute,
  BoilerDetailsIdRoute: BoilerDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
