/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoilerRouteImport } from './routes/boiler'
import { Route as CedRouteImport } from './routes/ced'
import { Route as ChecksheetRouteImport } from './routes/checksheet'
import { Route as ChecksheetApprovalRouteImport } from './routes/checksheet-approval'
import { Route as ChecksheetDailyRouteImport } from './routes/checksheet-daily'
import { Route as LogHistoryRouteImport } from './routes/log-history'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as OvenRouteImport } from './routes/oven'
import { Route as ReportRouteImport } from './routes/report'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as BoilerDetailsIdRouteImport } from './routes/boiler-details.$id'
import { Route as MasterDataIndexRouteImport } from './routes/master-data.index'
import { Route as MasterDataColorsRouteImport } from './routes/master-data.colors'
import { Route as MasterDataEquipmentRouteImport } from './routes/master-data.equipment'
import { Route as MasterDataStandardRouteImport } from './routes/master-data.standard'
import { Route as MasterDataStationRouteImport } from './routes/master-data.station'
import { Route as MasterDataTypeRouteImport } from './routes/master-data.type'
import { Route as MasterDataUomRouteImport } from './routes/master-data.uom'
import { Route as MonitoringAreaIndexRouteImport } from './routes/monitoring-area.index'
import { Route as MonitoringAreaIdRouteImport } from './routes/monitoring-area.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoilerRoute = BoilerRouteImport.update({
  id: '/boiler',
  path: '/boiler',
  getParentRoute: () => rootRouteImport,
} as any)
const CedRoute = CedRouteImport.update({
  id: '/ced',
  path: '/ced',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksheetRoute = ChecksheetRouteImport.update({
  id: '/checksheet',
  path: '/checksheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksheetApprovalRoute = ChecksheetApprovalRouteImport.update({
  id: '/checksheet-approval',
  path: '/checksheet-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksheetDailyRoute = ChecksheetDailyRouteImport.update({
  id: '/checksheet-daily',
  path: '/checksheet-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const LogHistoryRoute = LogHistoryRouteImport.update({
  id: '/log-history',
  path: '/log-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const OvenRoute = OvenRouteImport.update({
  id: '/oven',
  path: '/oven',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BoilerDetailsIdRoute = BoilerDetailsIdRouteImport.update({
  id: '/boiler-details/$id',
  path: '/boiler-details/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataIndexRoute = MasterDataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterDataRoute,
} as any)
const MasterDataColorsRoute = MasterDataColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => MasterDataRoute,
} as any)
const MasterDataEquipmentRoute = MasterDataEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => MasterDataRoute,
} as any)
const MasterDataStandardRoute = MasterDataStandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => MasterDataRoute,
} as any)
const MasterDataStationRoute = MasterDataStationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => MasterDataRoute,
} as any)
const MasterDataTypeRoute = MasterDataTypeRouteImport.update({
  id: '/type',
  path: '/type',
  getParentRoute: () => MasterDataRoute,
} as any)
const MasterDataUomRoute = MasterDataUomRouteImport.update({
  id: '/uom',
  path: '/uom',
  getParentRoute: () => MasterDataRoute,
} as any)
const MonitoringAreaIndexRoute = MonitoringAreaIndexRouteImport.update({
  id: '/monitoring-area/',
  path: '/monitoring-area/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringAreaIdRoute = MonitoringAreaIdRouteImport.update({
  id: '/monitoring-area/$id',
  path: '/monitoring-area/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boiler': typeof BoilerRoute
  '/ced': typeof CedRoute
  '/checksheet': typeof ChecksheetRoute
  '/checksheet-approval': typeof ChecksheetApprovalRoute
  '/checksheet-daily': typeof ChecksheetDailyRoute
  '/log-history': typeof LogHistoryRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/oven': typeof OvenRoute
  '/report': typeof ReportRoute
  '/user-management': typeof UserManagementRoute
  '/boiler-details/$id': typeof BoilerDetailsIdRoute
  '/master-data/colors': typeof MasterDataColorsRoute
  '/master-data/equipment': typeof MasterDataEquipmentRoute
  '/master-data/standard': typeof MasterDataStandardRoute
  '/master-data/station': typeof MasterDataStationRoute
  '/master-data/type': typeof MasterDataTypeRoute
  '/master-data/uom': typeof MasterDataUomRoute
  '/monitoring-area/$id': typeof MonitoringAreaIdRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/monitoring-area/': typeof MonitoringAreaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boiler': typeof BoilerRoute
  '/ced': typeof CedRoute
  '/checksheet': typeof ChecksheetRoute
  '/checksheet-approval': typeof ChecksheetApprovalRoute
  '/checksheet-daily': typeof ChecksheetDailyRoute
  '/log-history': typeof LogHistoryRoute
  '/oven': typeof OvenRoute
  '/report': typeof ReportRoute
  '/user-management': typeof UserManagementRoute
  '/boiler-details/$id': typeof BoilerDetailsIdRoute
  '/master-data/colors': typeof MasterDataColorsRoute
  '/master-data/equipment': typeof MasterDataEquipmentRoute
  '/master-data/standard': typeof MasterDataStandardRoute
  '/master-data/station': typeof MasterDataStationRoute
  '/master-data/type': typeof MasterDataTypeRoute
  '/master-data/uom': typeof MasterDataUomRoute
  '/monitoring-area/$id': typeof MonitoringAreaIdRoute
  '/master-data': typeof MasterDataIndexRoute
  '/monitoring-area': typeof MonitoringAreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boiler': typeof BoilerRoute
  '/ced': typeof CedRoute
  '/checksheet': typeof ChecksheetRoute
  '/checksheet-approval': typeof ChecksheetApprovalRoute
  '/checksheet-daily': typeof ChecksheetDailyRoute
  '/log-history': typeof LogHistoryRoute
  '/master-data': typeof MasterDataRouteWithChildren
  '/oven': typeof OvenRoute
  '/report': typeof ReportRoute
  '/user-management': typeof UserManagementRoute
  '/boiler-details/$id': typeof BoilerDetailsIdRoute
  '/master-data/colors': typeof MasterDataColorsRoute
  '/master-data/equipment': typeof MasterDataEquipmentRoute
  '/master-data/standard': typeof MasterDataStandardRoute
  '/master-data/station': typeof MasterDataStationRoute
  '/master-data/type': typeof MasterDataTypeRoute
  '/master-data/uom': typeof MasterDataUomRoute
  '/monitoring-area/$id': typeof MonitoringAreaIdRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/monitoring-area/': typeof MonitoringAreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boiler'
    | '/ced'
    | '/checksheet'
    | '/checksheet-approval'
    | '/checksheet-daily'
    | '/log-history'
    | '/master-data'
    | '/oven'
    | '/report'
    | '/user-management'
    | '/boiler-details/$id'
    | '/master-data/colors'
    | '/master-data/equipment'
    | '/master-data/standard'
    | '/master-data/station'
    | '/master-data/type'
    | '/master-data/uom'
    | '/monitoring-area/$id'
    | '/master-data/'
    | '/monitoring-area/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boiler'
    | '/ced'
    | '/checksheet'
    | '/checksheet-approval'
    | '/checksheet-daily'
    | '/log-history'
    | '/oven'
    | '/report'
    | '/user-management'
    | '/boiler-details/$id'
    | '/master-data/colors'
    | '/master-data/equipment'
    | '/master-data/standard'
    | '/master-data/station'
    | '/master-data/type'
    | '/master-data/uom'
    | '/monitoring-area/$id'
    | '/master-data'
    | '/monitoring-area'
  id:
    | '__root__'
    | '/'
    | '/boiler'
    | '/ced'
    | '/checksheet'
    | '/checksheet-approval'
    | '/checksheet-daily'
    | '/log-history'
    | '/master-data'
    | '/oven'
    | '/report'
    | '/user-management'
    | '/boiler-details/$id'
    | '/master-data/colors'
    | '/master-data/equipment'
    | '/master-data/standard'
    | '/master-data/station'
    | '/master-data/type'
    | '/master-data/uom'
    | '/monitoring-area/$id'
    | '/master-data/'
    | '/monitoring-area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoilerRoute: typeof BoilerRoute
  CedRoute: typeof CedRoute
  ChecksheetRoute: typeof ChecksheetRoute
  ChecksheetApprovalRoute: typeof ChecksheetApprovalRoute
  ChecksheetDailyRoute: typeof ChecksheetDailyRoute
  LogHistoryRoute: typeof LogHistoryRoute
  MasterDataRoute: typeof MasterDataRouteWithChildren
  OvenRoute: typeof OvenRoute
  ReportRoute: typeof ReportRoute
  UserManagementRoute: typeof UserManagementRoute
  BoilerDetailsIdRoute: typeof BoilerDetailsIdRoute
  MonitoringAreaIdRoute: typeof MonitoringAreaIdRoute
  MonitoringAreaIndexRoute: typeof MonitoringAreaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boiler': {
      id: '/boiler'
      path: '/boiler'
      fullPath: '/boiler'
      preLoaderRoute: typeof BoilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ced': {
      id: '/ced'
      path: '/ced'
      fullPath: '/ced'
      preLoaderRoute: typeof CedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checksheet': {
      id: '/checksheet'
      path: '/checksheet'
      fullPath: '/checksheet'
      preLoaderRoute: typeof ChecksheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checksheet-approval': {
      id: '/checksheet-approval'
      path: '/checksheet-approval'
      fullPath: '/checksheet-approval'
      preLoaderRoute: typeof ChecksheetApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checksheet-daily': {
      id: '/checksheet-daily'
      path: '/checksheet-daily'
      fullPath: '/checksheet-daily'
      preLoaderRoute: typeof ChecksheetDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-history': {
      id: '/log-history'
      path: '/log-history'
      fullPath: '/log-history'
      preLoaderRoute: typeof LogHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oven': {
      id: '/oven'
      path: '/oven'
      fullPath: '/oven'
      preLoaderRoute: typeof OvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boiler-details/$id': {
      id: '/boiler-details/$id'
      path: '/boiler-details/$id'
      fullPath: '/boiler-details/$id'
      preLoaderRoute: typeof BoilerDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/': {
      id: '/master-data/'
      path: '/'
      fullPath: '/master-data/'
      preLoaderRoute: typeof MasterDataIndexRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/master-data/colors': {
      id: '/master-data/colors'
      path: '/colors'
      fullPath: '/master-data/colors'
      preLoaderRoute: typeof MasterDataColorsRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/master-data/equipment': {
      id: '/master-data/equipment'
      path: '/equipment'
      fullPath: '/master-data/equipment'
      preLoaderRoute: typeof MasterDataEquipmentRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/master-data/standard': {
      id: '/master-data/standard'
      path: '/standard'
      fullPath: '/master-data/standard'
      preLoaderRoute: typeof MasterDataStandardRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/master-data/station': {
      id: '/master-data/station'
      path: '/station'
      fullPath: '/master-data/station'
      preLoaderRoute: typeof MasterDataStationRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/master-data/type': {
      id: '/master-data/type'
      path: '/type'
      fullPath: '/master-data/type'
      preLoaderRoute: typeof MasterDataTypeRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/master-data/uom': {
      id: '/master-data/uom'
      path: '/uom'
      fullPath: '/master-data/uom'
      preLoaderRoute: typeof MasterDataUomRouteImport
      parentRoute: typeof MasterDataRoute
    }
    '/monitoring-area/': {
      id: '/monitoring-area/'
      path: '/monitoring-area'
      fullPath: '/monitoring-area/'
      preLoaderRoute: typeof MonitoringAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring-area/$id': {
      id: '/monitoring-area/$id'
      path: '/monitoring-area/$id'
      fullPath: '/monitoring-area/$id'
      preLoaderRoute: typeof MonitoringAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MasterDataRouteChildren {
  MasterDataColorsRoute: typeof MasterDataColorsRoute
  MasterDataEquipmentRoute: typeof MasterDataEquipmentRoute
  MasterDataStandardRoute: typeof MasterDataStandardRoute
  MasterDataStationRoute: typeof MasterDataStationRoute
  MasterDataTypeRoute: typeof MasterDataTypeRoute
  MasterDataUomRoute: typeof MasterDataUomRoute
  MasterDataIndexRoute: typeof MasterDataIndexRoute
}

const MasterDataRouteChildren: MasterDataRouteChildren = {
  MasterDataColorsRoute: MasterDataColorsRoute,
  MasterDataEquipmentRoute: MasterDataEquipmentRoute,
  MasterDataStandardRoute: MasterDataStandardRoute,
  MasterDataStationRoute: MasterDataStationRoute,
  MasterDataTypeRoute: MasterDataTypeRoute,
  MasterDataUomRoute: MasterDataUomRoute,
  MasterDataIndexRoute: MasterDataIndexRoute,
}

const MasterDataRouteWithChildren = MasterDataRoute._addFileChildren(
  MasterDataRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoilerRoute: BoilerRoute,
  CedRoute: CedRoute,
  ChecksheetRoute: ChecksheetRoute,
  ChecksheetApprovalRoute: ChecksheetApprovalRoute,
  ChecksheetDailyRoute: ChecksheetDailyRoute,
  LogHistoryRoute: LogHistoryRoute,
  MasterDataRoute: MasterDataRouteWithChildren,
  OvenRoute: OvenRoute,
  ReportRoute: ReportRoute,
  UserManagementRoute: UserManagementRoute,
  BoilerDetailsIdRoute: BoilerDetailsIdRoute,
  MonitoringAreaIdRoute: MonitoringAreaIdRoute,
  MonitoringAreaIndexRoute: MonitoringAreaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
